# Generated by Django 5.1 on 2024-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=123, upload_to='book_media'),
            preserve_default=False,
        ),
    ]
